name: ini workflow cd
on:
  push:
    branches:
      - "master"
jobs:
  ini-jobs-cd:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ini adalah cd"
  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 190022/order-kafe:latest

      - name: ssh aws ec2 and redeploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop order_kafe
            docker container rm order_kafe
            docker pull fahmihadi/order-kafe:latest
            docker run -p 80:8888 --name order_kafe --detach fahmihadi/order-kafe:latest